Add SigData to QuickSignResponse
kadena-io/signing-api pull request #10
Opened 2021-06-09 16:01 UTC by jmininger

Adds the SigData type to the quicksignresponse type, which requires bumping pact, which requires ripping the Swagger orphans out of an older version of pact and plopping them in our own docs repo until we come up with a better solution.
Note: Im merging into the quicksign branch, not master, so as not to dirty anything up

2021-06-09 16:39 UTC, mightybyte requested changes

2021-06-09 16:39 UTC, mightybyte commented on kadena-signing-api/src/Kadena/SigningApi.hs
> +    results <- o .: "resuls"
Typo in the key

2021-06-09 16:47 UTC, jmininger commented on kadena-signing-api/src/Kadena/SigningApi.hs
> +    results <- o .: "resuls"
fixed

2021-07-07 15:42 UTC, mightybyte approved these changes

2021-07-07 15:48 UTC, merged